# Jekyll configuration for GitHub Pages
title: Dispatches
description: Remarks long-and-short.
author: Your Name
email: your-email@example.com

# Theme
theme: jekyll-theme-dinky

# Permalink structure for nice URLs
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
  notes:
    output: true
    permalink: /notes/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "page"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor/
  - justfile
